use modelador

ALTER TABLE COTIZACION 
ADD OBS VARCHAR(300)

ALTER TABLE COTIZACION 
ADD RGS NUMERIC (5,3) DEFAULT 0

ALTER TABLE COTIZACION 
ADD MTELA NUMERIC (5,3) DEFAULT 0

ALTER TABLE COTIZACION 
ADD MPDA NUMERIC (5,3) DEFAULT 0

ALTER TABLE COTIZACION 
ADD TIPEMB CHAR(1) DEFAULT 'S'

ALTER TABLE  TB_CTRL
ADD FACTOR1 FLOAT

ALTER TABLE  TB_CTRL
ADD FACTOR2 FLOAT

UPDATE TB_CTRL SET VALORMIN= 0.07
UPDATE TB_CTRL SET DBACK= 5
UPDATE TB_CTRL SET RENTA= 20
UPDATE TB_CTRL SET COBERTURA =5
UPDATE TB_CTRL SET FACTOR1 =0.12
UPDATE TB_CTRL SET FACTOR2 =4
