SELECT T.TELA, T.DESCRIPCION, T.HIL1, T.POR1 AS [%1], M1.DESCRIPCION AS F1, H1.DESCRIPCION AS DES1, 
T.HIL2, T.POR2 AS [%2], M2.DESCRIPCION AS F2, H2.DESCRIPCION AS DES2, 
T.HIL3, T.POR3 AS [%3], M3.DESCRIPCION AS F3, H3.DESCRIPCION AS DES3,
T.HIL4, T.POR4 AS [%4], M4.DESCRIPCION AS F4, H4.DESCRIPCION AS DES4, 
T.HIL5, T.POR5 AS [%5], M5.DESCRIPCION AS F5, H5.DESCRIPCION AS DES5,
T.HIL6, T.POR6 AS [%6], M6.DESCRIPCION AS F6, H6.DESCRIPCION AS DES6, 
SUBSTRING(H1.TITULO,1,3)+'/'+ SUBSTRING(H1.TITULO,4,1) AS TIT1,
SUBSTRING(H2.TITULO,1,3)+'/'+ SUBSTRING(H2.TITULO,4,1) AS TIT2,
SUBSTRING(H3.TITULO,1,3)+'/'+ SUBSTRING(H3.TITULO,4,1) AS TIT3,
SUBSTRING(H4.TITULO,1,3)+'/'+ SUBSTRING(H4.TITULO,4,1) AS TIT4,
SUBSTRING(H5.TITULO,1,3)+'/'+ SUBSTRING(H5.TITULO,4,1) AS TIT5,
SUBSTRING(H6.TITULO,1,3)+'/'+ SUBSTRING(H6.TITULO,4,1) AS TIT6
FROM TELAS AS T 
INNER JOIN HILADO AS H1 ON T.HIL1 COLLATE DATABASE_DEFAULT = H1.HILO COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN HILADO AS H2 ON T.HIL2 COLLATE DATABASE_DEFAULT = H2.HILO COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN HILADO AS H3 ON T.HIL3 COLLATE DATABASE_DEFAULT = H3.HILO COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN HILADO AS H4 ON T.HIL4 COLLATE DATABASE_DEFAULT = H4.HILO COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN HILADO AS H5 ON T.HIL5 COLLATE DATABASE_DEFAULT = H5.HILO COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN HILADO AS H6 ON T.HIL6 COLLATE DATABASE_DEFAULT = H6.HILO COLLATE DATABASE_DEFAULT 
INNER JOIN MATERIA AS M1 ON H1.FIBRA = M1.CODIGO 
LEFT OUTER JOIN MATERIA AS M2 ON H2.FIBRA = M2.CODIGO
LEFT OUTER JOIN MATERIA AS M3 ON H3.FIBRA = M3.CODIGO
LEFT OUTER JOIN MATERIA AS M4 ON H4.FIBRA = M4.CODIGO
LEFT OUTER JOIN MATERIA AS M5 ON H5.FIBRA = M5.CODIGO
LEFT OUTER JOIN MATERIA AS M6 ON H6.FIBRA = M6.CODIGO 
WHERE T.TELA ='700001'  