ALTER TABLE COTIZACION
ADD RENDIMIENTO FLOAT

GO

ALTER TABLE COTIZACION
ADD CONSUMO FLOAT


-- SELECT * FROM TELARUTAHEAD order by 1
-- SELECT * FROM COTIZACION

-- SELECT * FROM COTIruta

--select * from [proto-detalles] order by 4