ALTER TABLE pos add
HOUSE NUMERIC(5,2) DEFAULT 0,
LLEGAPO SMALLDATETIME DEFAULT GETDATE(),
BIG NUMERIC (18,2) DEFAULT 0,
OBSERVA VARCHAR(150) DEFAULT '' 
GO
alter table TB_CTRL add
HOUSE	numeric (5,2),
BIG		NUMERIC (5,2)
GO

UPDATE TB_CTRL SET
HOUSE = 0.09,
BIG = 1.25 
GO

