SELECT CLIENTE, RIGHT(LTRIM(RTRIM(CODARTICULO)),5) as codi, COUNT(RIGHT(LTRIM(RTRIM(CODARTICULO)),5)) count, CLIENTE.NOMBRE, ESTCLI
FROM ESTILOS inner join CLIENTE on CLIENTE = CLIENTE.CODIGO
WHERE ESTILOS.ESTADO = 'A'
GROUP BY CLIENTE, nombre, ESTCLI, 
RIGHT(LTRIM(RTRIM(CODARTICULO)),5)
Having
COUNT(RIGHT(LTRIM(RTRIM(CODARTICULO)),5)) > 1 AND RIGHT(LTRIM(RTRIM(CODARTICULO)),5) <> ''   
ORDER BY codi




select * from estilos where RIGHT(LTRIM(RTRIM(CODARTICULO)),5) = '17930'
/*UPDATE ESTILOS SET ESTADO ='E' WHERE CLIENTE = '00001' AND CODEST  = '00249'
*/
--select * from TB_CTRL