

CREATE TABLE [CODTALLA] (
		[CODIGO]      char(3) NOT NULL PRIMARY KEY,
		[DESCRIPCION] char(15) NOT NULL,
		[USUARIO]     char(10) NOT NULL,
		[FECHA]		  SMALLDATETIME DEFAULT GETDATE() NOT NULL,
		[ESTADO]	  CHAR(1) DEFAULT 'A' NOT NULL
)
ON [PRIMARY]
GO

