USE MODELADOR
GO

CREATE TABLE [dbo].[EXPLOSION_TELA](
	[OFI]		char(8) NOT NULL ,
	[PO]		CHAR(20) NOT NULL DEFAULT '',
	[UBI]		INT	NOT NULL DEFAULT 0,
	[ID]		INT	NOT NULL DEFAULT 0,
	[COMBO]		VARCHAR(100) NOT NULL DEFAULT '',
	[ETC]		CHAR(10) NOT NULL DEFAULT '',
	[CRUDO]		CHAR(6) NOT NULL DEFAULT '',
	[QTY]		NUMERIC (18,2)	NOT NULL DEFAULT 0,
	[KGS]		NUMERIC (18,2)	NOT NULL DEFAULT 0,
	[COLPZA]	VARCHAR(100) NOT NULL DEFAULT '',
	[TELA]		CHAR(16) NOT NULL DEFAULT '',
	[H1]		CHAR(12) NOT NULL DEFAULT '',
	[P1]		FLOAT NOT NULL DEFAULT 0,
	[K1]		NUMERIC (18,2)	NOT NULL DEFAULT 0,	
	[H2]		CHAR(12) NOT NULL DEFAULT '',
	[P2]		FLOAT	NOT NULL DEFAULT 0,
	[K2]		NUMERIC (18,2)	NOT NULL DEFAULT 0,	
	[H3]		CHAR(12) NOT NULL DEFAULT '',
	[P3]		FLOAT NOT NULL DEFAULT 0,
	[K3]		NUMERIC (18,2)	NOT NULL DEFAULT 0,	
	[H4]		CHAR(12) NOT NULL DEFAULT '',
	[P4]		FLOAT NOT NULL DEFAULT 0,
	[K4]		NUMERIC (18,2)	NOT NULL DEFAULT 0,	
	[H5]		CHAR(12) NOT NULL DEFAULT '',
	[P5]		FLOAT NOT NULL DEFAULT 0,
	[K5]		NUMERIC (18,2)	NOT NULL DEFAULT 0,	
	[H6]		CHAR(12) NOT NULL DEFAULT '',
	[P6]		FLOAT NOT NULL DEFAULT 0,
	[K6]		NUMERIC (18,2)	NOT NULL DEFAULT 0,	
	[USUARIO]	CHAR(10),
	[FECHA]		[SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO]	CHAR(1) DEFAULT 'A',
	 CONSTRAINT [PK_EXPLO] PRIMARY KEY CLUSTERED 
(	[OFI]	ASC,
	[PO]	ASC,
	[UBI]	ASC,
	[ID]	ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

