USE MODELADOR
GO
/*
DROP TABLE ETC_DETA
DROP TABLE ETC
*/
select * into etcold from etc
select * into etc_detaold from etc_deta


insert into ETC SELECT CODETC,CODCLI,CODEST,CODTEM, 'T', DES0,des1,DES2,DES3,DES4,DES5,DES6,DES7,DES8,DES9,'','','','','',
USUARIO, FECHA, ESTADO FROM ETCOLD



insert into ETC_deta SELECT CODETC,'T',ubi,combo, COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9,'','','','','',
USUARIO, FECHA, ESTADO FROM ETc_detaOLD WHERE CODETC= '0000000004'



CREATE TABLE [dbo].[ETC](
	[CODETC] [char](10) NOT NULL ,
	[CODCLI] CHAR(5) ,
	[CODEST] CHAR(5) ,
	[CODTEM] CHAR(4) ,
	[CODTIP] CHAR(1) NOT NULL DEFAULT 'T',
	[DES01]		[VARchar](100) NOT NULL DEFAULT '',
	[DES02]		[VARchar](100) NOT NULL DEFAULT '',
	[DES03]		[VARchar](100) NOT NULL DEFAULT '',
	[DES04]		[VARchar](100) NOT NULL DEFAULT '',
	[DES05]		[VARchar](100) NOT NULL DEFAULT '',
	[DES06]		[VARchar](100) NOT NULL DEFAULT '',
	[DES07]		[VARchar](100) NOT NULL DEFAULT '',
	[DES08]		[VARchar](100) NOT NULL DEFAULT '',
	[DES09]		[VARchar](100) NOT NULL DEFAULT '',
	[DES10]		[VARchar](100) NOT NULL DEFAULT '',
	[DES11]		[VARchar](100) NOT NULL DEFAULT '',
	[DES12]		[VARchar](100) NOT NULL DEFAULT '',
	[DES13]		[VARchar](100) NOT NULL DEFAULT '',
	[DES14]		[VARchar](100) NOT NULL DEFAULT '',
	[DES15]		[VARchar](100) NOT NULL DEFAULT '',
	[USUARIO] CHAR(10),
	[FECHA] [SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO] CHAR(1) DEFAULT 'A',
	 CONSTRAINT [PK_ETC] PRIMARY KEY CLUSTERED 
(	[CODETC] ASC,
	[CODTIP]	ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE INDEX P_ETC
ON ETC (CODCLI,CODEST, CODTEM)
GO

CREATE TABLE [dbo].[ETC_DETA](
	[CODETC]	[char](10) NOT NULL ,
	[CODTIP]	[CHAR](1) NOT NULL DEFAULT 'T',
	[UBI]		[char](3) NOT NULL ,
	[COMBO]		[VARchar](100) NOT NULL DEFAULT '',
	[COL01]		[VARchar](30) NOT NULL DEFAULT '',
	[COL02]		[VARchar](30) NOT NULL DEFAULT '',
	[COL03]		[VARchar](30) NOT NULL DEFAULT '',
	[COL04]		[VARchar](30) NOT NULL DEFAULT '',
	[COL05]		[VARchar](30) NOT NULL DEFAULT '',
	[COL06]		[VARchar](30) NOT NULL DEFAULT '',
	[COL07]		[VARchar](30) NOT NULL DEFAULT '',
	[COL08]		[VARchar](30) NOT NULL DEFAULT '',
	[COL09]		[VARchar](30) NOT NULL DEFAULT '',
	[COL10]		[VARchar](30) NOT NULL DEFAULT '',
	[COL11]		[VARchar](30) NOT NULL DEFAULT '',
	[COL12]		[VARchar](30) NOT NULL DEFAULT '',
	[COL13]		[VARchar](30) NOT NULL DEFAULT '',
	[COL14]		[VARchar](30) NOT NULL DEFAULT '',
	[COL15]		[VARchar](30) NOT NULL DEFAULT '',
	[USUARIO]	[CHAR](10),
	[FECHA]		[SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO]	[CHAR](1) DEFAULT 'A',
 CONSTRAINT [PK_ETC_DETA] PRIMARY KEY CLUSTERED 
(	[CODETC] ASC,
	[CODTIP]	ASC,
	[UBI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

