USE [MODELADOR]
GO

DROP TABLE MATRIZ_COMPRA_TELA
GO
CREATE TABLE [dbo].[MATRIZ_COMPRA_TELA](
	[CODIGO]	CHAR(3)		PRIMARY KEY,
	[TIPO]		CHAR(1)		, -- C = COMPRA, S = SERVICIO
	[MOVIM]		VARCHAR(100),
	[ALMORI]	CHAR(4)		,
	[ALMDES]	CHAR(4)		,
	[CODSER]	CHAR(10)	,
	[ENTREGA]	VARCHAR(100),
	[RECIBE]	VARCHAR(100),
	[USUARIO]	CHAR(10)	,
	[FECHA]		SMALLDATETIME
) ON [PRIMARY]
--SELECT * FROM RSFACCAR..AL0001ARTI WHERE AR_CDESCRI LIKE '%SERVICIO%' or AR_CCODIGO like 'ST0%'


INSERT INTO MATRIZ_COMPRA_TELA SELECT '001','C', 'COMPRA HILO CRUDO',	'', '00H0','','','HILO CRUDO',	'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '002','C', 'COMPRA HILO COLOR',	'', '00HT','','','HILO CRUDO',	'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '003','C', 'COMPRA TELA CRUDA',	'', '00M0','','','TELA CRUDO',	'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '004','C', 'COMPRA TELA COLOR',	'', '00M7','','','TELA COLOR',	'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '005','C', 'COMPRA TELA ACABADA',	'', '00MD','','','TELA ACABADA','SISTEMAS', GETDATE() 

INSERT INTO MATRIZ_COMPRA_TELA SELECT '006','S', 'TEÑIDO DE HILO',		'00H0', '00HT','ST015','HILO CRUDO','HILO COLOR',	'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '007','S', 'TEJIDO EN CRUDO',		'00H0', '00M0','ST006','HILO CRUDO','TELA CRUDA',	'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '008','S', 'TEJIDO EN COLOR',		'00HT', '00M7','ST101','HILO COLOR','TELA COLOR',	'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '009','S', 'TEÑIDO DE TELA',		'00M0', '00M7','ST015','TELA CRUDA','TELA COLOR',	'SISTEMAS', GETDATE() 

INSERT INTO MATRIZ_COMPRA_TELA SELECT '010','S', 'ESTAMPADO DE TELA',	'00M7', '00MD','ST008','TELA COLOR','TELA ACABADA', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '011','S', 'LAVADO DE TELA',		'00M7', '00MD','ST9031','TELA COLOR','TELA ACABADA', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '012','S', 'ACABADO DE TELA',		'00M7', '00MD','ST023','TELA COLOR','TELA ACABADA', 'SISTEMAS', GETDATE() 
GO
SELECT * FROM MATRIZ_COMPRA_TELA