CREATE TABLE ORDENCOMPRA (
NUMORD		CHAR(10) not null,
ITEM		CHAR(4)  NOT NULL,
SUB_IT		CHAR(2)  NOT NULL,
OFI			CHAR(8)  NOT NULL,
CODIGO		CHAR(25) NOT NULL,
CANTIDAD	NUMERIC(13,3),
USUARIO		CHAR(10),
FECHA		SMALLDATETIME NOT NULL DEFAULT GETDATE(),
ESTADO		CHAR(1) NOT NULL DEFAULT 'A'
)
GO
ALTER TABLE [ORDENCOMPRA]
	ADD
	CONSTRAINT [PK_ORDENCOMPRA]
	PRIMARY KEY
	([NUMORD],[ITEM],[SUB_IT])
	ON [PRIMARY]
GO
