
GO
/*DROP TABLE SPECS_MAQUINAS
DROP TABLE MAQUINAS
*/

CREATE TABLE [dbo].[MAQUINAS](
	[CODIGO] [char](3) NOT NULL PRIMARY KEY,
	[DESCRIPCION] VARCHAR(50) ,
	[USUARIO] CHAR(10),
	[FECHA] [SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO] CHAR(1) DEFAULT 'A'
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SPECS_MAQUINAS](
	[SPEC]		[char](10) NOT NULL ,
	[VER]		[char](3) NOT NULL ,
	[LIN]		[CHAR](2) NOT NULL DEFAULT '',
	[MAQ]		[char](3) NOT NULL REFERENCES [MAQUINAS](CODIGO),
	[PUNTOS]	[char](12),
	[MEDIDA]	[CHAR](8),
	[HILOS]		[CHAR](4),
	[USUARIO]	[CHAR](10),
	[FECHA]		[SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO]	[CHAR](1) DEFAULT 'A',
 CONSTRAINT [PK_SPECRU] PRIMARY KEY CLUSTERED 
(	[SPEC] ASC,
	[VER] ASC,
	[LIN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]



/*DROP TABLE SPECS_boton

*/

CREATE TABLE [dbo].[SPECS_BOTON](
	[SPEC]		[char](10) NOT NULL ,
	[VER]		[char](3) NOT NULL ,
	[LINEAS]	INT,
	[HUECOS]	INT,
	[COLOR]		[VARCHAR](30),
	[HILO1]		[VARCHAR](30),
	[COSTURA]	[CHAR](1),
	[OJAL]		[VARCHAR](100),
	[TAMANO]	[CHAR](8),
	[HILO2]		[VARCHAR](30),
	[CANTIDAD]	INT,
	[USUARIO]	[CHAR](10),
	[FECHA]		[SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO]	[CHAR](1) DEFAULT 'A',
 CONSTRAINT [PK_SPEBOT] PRIMARY KEY CLUSTERED 
(	[SPEC] ASC,
	[VER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


SELECT * FROM SUBMENU
