USE MODELADOR
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =================================================
-- Author:		MABEL MOLINA
-- Create date: 18-FEB-2013
-- Description:	CALCULA POR ID DEL PROTO EL CONSUMO
--				DE TELA POR TALLA COLOR DE LA OFI
-- =================================================
alter PROCEDURE DATOS_CORTE_OFI
	-- Add the parameters for the stored procedure here
	@OFI CHAR(10)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
    SELECT	DISTINCT	PP.color , PD.ID, PD.ADICIONAL AS OBS,
			T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, 
			SUM((CAN0 * CC.COBERTURA/100)+Can0) AS C0, SUM((CAN1 * CC.COBERTURA/100)+can1) AS C1, 
			SUM((CAN2 * CC.COBERTURA/100)+can2) AS C2, SUM((CAN3 * cc.COBERTURA/100)+can3) AS C3, 
			SUM((CAN4 * cc.cobertura/100)+can4) AS C4, SUM((CAN5 * CC.COBERTURA/100)+can5) AS C5, 
			SUM((CAN6 * CC.COBERTURA/100)+can6) AS C6, SUM((CAN7 * CC.COBERTURA/100)+can7) AS C7,
			SUM((CAN8 * CC.COBERTURA/100)+can8) AS C8, SUM((CAN9 * CC.COBERTURA/100)+can9) AS C9,
			
			SUM(((CAN0 * CC.COBERTURA/100)+ Can0)* (PD.CONSUMO/CANPZA)* FACTOR) AS MT0,
			SUM(((CAN1 * CC.COBERTURA/100)+ Can1)* (PD.CONSUMO/CANPZA)* FACTOR) AS MT1, 
			SUM(((CAN2 * CC.COBERTURA/100)+ Can2)* (PD.CONSUMO/CANPZA)* FACTOR) AS MT2,
			SUM(((CAN3 * CC.COBERTURA/100)+ Can3)* (PD.CONSUMO/CANPZA)* FACTOR) AS MT3,
			SUM(((CAN4 * CC.COBERTURA/100)+ Can4)* (PD.CONSUMO/CANPZA)* FACTOR) AS MT4,
			SUM(((CAN5 * CC.COBERTURA/100)+ Can5)* (PD.CONSUMO/CANPZA)* FACTOR) AS MT5,
			SUM(((CAN6 * CC.COBERTURA/100)+ Can6)* (PD.CONSUMO/CANPZA)* FACTOR) AS MT6,
			SUM(((CAN7 * CC.COBERTURA/100)+ Can7)* (PD.CONSUMO/CANPZA)* FACTOR) AS MT7,
			SUM(((CAN8 * CC.COBERTURA/100)+ Can8)* (PD.CONSUMO/CANPZA)* FACTOR) AS MT8,
			SUM(((CAN9 * CC.COBERTURA/100)+ Can9)* (PD.CONSUMO/CANPZA)* FACTOR) AS MT9,
			
			SUM(((CAN0 * CC.COBERTURA/100) + Can0) * PESO/1000) AS KG0,
			SUM(((CAN1 * CC.COBERTURA/100) + Can1) * PESO/1000 ) AS KG1, 
			SUM(((CAN2 * CC.COBERTURA/100) + Can2) * PESO/1000 ) AS KG2,
			SUM(((CAN3 * CC.COBERTURA/100) + Can3) * PESO/1000 ) AS KG3,
			SUM(((CAN4 * CC.COBERTURA/100) + Can4) * PESO/1000 ) AS KG4,
			SUM(((CAN5 * CC.COBERTURA/100) + Can5) * PESO/1000 ) AS KG5,
			SUM(((CAN6 * CC.COBERTURA/100) + Can6) * PESO/1000 ) AS KG6,
			SUM(((CAN7 * CC.COBERTURA/100) + Can7) * PESO/1000 ) AS KG7,
			SUM(((CAN8 * CC.COBERTURA/100) + Can8) * PESO/1000 ) AS KG8,
			SUM(((CAN9 * CC.COBERTURA/100) + Can9) * PESO/1000 ) AS KG9
			
	FROM		[PO-DETA] AS PP 
	INNER JOIN POS ON POS.PO = PP.PO
	INNER JOIN COTIZACION CC ON CC.COTIZACION = POS.COTIZACION
	INNER JOIN PROTOS AS PRO ON CC.PROTO = PRO.PROTO AND CC.[VERSION] = PRO.[VERSION]
	INNER JOIN [PROTO-DETALLES] PD ON PRO.PROTO = PD.PROTO AND PRO.[VERSION] = PD.[VERSION]
	inner join ofi_pos OP ON OP.PO = POS.PO
	WHERE  OP.OFI = @OFI AND PD.TIPODETALLE = 'TE'
	and PP.estado = 'A'
GROUP BY PP.COLOR, T0, T1,T2, T3,T4,T5,T6,T7,T8,T9, PD.ID, PD.ADICIONAL
    
	END
GO
