
-- DISPONIBLE POR TALLA - ALMACEN

select CAN =SUM(CASE WHEN BB.CTIPMOV = 'E' THEN CANTIDAD ELSE CANTIDAD * -1 END), TALLA
from multi..RS_ALMOVD_TALLA0001 as aa
inner join multi..RS_ALMOVD0001 as bb on 
aa.calma COLLATE Modern_Spanish_CI_AS = bb.calma and aa.cnumdoc COLLATE Modern_Spanish_CI_AS = bb.CNUMDOC
AND BB.CITEM = AA.CITEM COLLATE Modern_Spanish_CI_AS
where AA.CALMA = '00md'   AND CCODIGO = '9000170509004300' 
GROUP BY TALLA , ORDEN
ORDER BY ORDEN


-- DISPONIBLE TOTAL SIN DISCRIMINAR
SELECT DISTINCT
DISPONIBLE= (select SK_NSKDIS - (select CAN = CASE  WHEN SUM(QTY) > 0 THEN SUM(QTY) WHEN SUM(KGS) > 0 THEN SUM(KGS) ELSE 0 END from rsv_tela  
where CODIGO = '9000170509004300')  
from rsfaccar..AL0001STOC where sk_calma='00MD' and sk_ccodigo= '9000170509004300')


-- DISPONIBLE POR TALLA
select CAN =SUM(CASE WHEN BB.CTIPMOV = 'E' THEN CANTIDAD ELSE CANTIDAD * -1 END) from multi..RS_ALMOVD_TALLA0001 as aa inner join multi..RS_ALMOVD0001 as bb on aa.calma COLLATE Modern_Spanish_CI_AS = bb.calma and aa.cnumdoc COLLATE Modern_Spanish_CI_AS = bb.CNUMDOC AND BB.CITEM = AA.CITEM COLLATE Modern_Spanish_CI_AS where AA.CALMA='00MD' AND CCODIGO='9000170509004300' AND TALLA='S' 
