Select * From RSFACCAR..AL0001TABL Where TG_CCOD='31' Order by TG_CCLAVE
go
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='63' Order by TG_CCLAVE
go
Select OC_CNUMORD AS Cadebus, IMPORTE=CASE OC_CCODMON When 'US' Then OC_NIMPUS Else OC_NIMPMN END, TG_CDESCRI AS ESTADO, *  From RSFACCAR..CO0001MOVC Left Join RSFACCAR..AL0001TABL On 
OC_CSITORD=TG_CCLAVE  Where TG_CCOD='31'  And (YEAR(CONVERT(DATETIME,OC_DFECDOC,103))= YEAR(Convert(datetime,'01/12/2012',103)) and MONTH(CONVERT(DATETIME,OC_DFECDOC,103))= 
MONTH(Convert(datetime,'01/12/2012',103))) Order by OC_CNUMORD,OC_DFECDOC
go
Select OC_CNUMORD AS Cadebus, IMPORTE=CASE OC_CCODMON When 'US' Then OC_NIMPUS Else OC_NIMPMN END, TG_CDESCRI AS ESTADO, *  From RSFACCAR..CO0001MOVC Left Join RSFACCAR..AL0001TABL On 
OC_CSITORD=TG_CCLAVE  Where TG_CCOD='31'  And (YEAR(CONVERT(DATETIME,OC_DFECDOC,103))= YEAR(Convert(datetime,'01/12/2012',103)) and MONTH(CONVERT(DATETIME,OC_DFECDOC,103))= 
MONTH(Convert(datetime,'01/12/2012',103))) Order by OC_CNUMORD,OC_DFECDOC
go
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='21' And TG_CCLAVE='OC'
go
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='94' And LEFT(TG_CCLAVE,3)='COM'
go
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And LEFT(TG_CCLAVE,7)='PULWORD'
go
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And LEFT(TG_CCLAVE,7)='MODICOM'
go
Select OC_CSITORD,OC_CTIPORD From RSFACCAR..CO0001MOVC Where OC_CNUMORD='0000022464          '
go
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='94' And TG_CCLAVE='COM'
go
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='94' And TG_CCLAVE='COMI'
go
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='94' And TG_CCLAVE='COMS'
go
Select * From RSFACCAR..CO0001MOVC LEFT OUTER JOIN RSCONCAR..CP0001MAES on AC_CVANEXO='P' AND AC_CCODIGO=OC_CCODPRO Where OC_CNUMORD='0000022464' And OC_CTIPORD='N'
go
Select AC_CFAX From RSFACCAR..ALCIAS Where AC_CCIA='0001'
go
Select AC_CTELEF1 From RSFACCAR..ALCIAS Where AC_CCIA='0001'
go
Select * From RSFACCAR..CO0001MOVD Where OC_CNUMORD='0000022464          '
go
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='27' AND TG_CCLAVE=''
go
