
SELECT * from RS_ALMOV_UBICACION where CALMA='00HS'

-- EL INSERT ES MANUAL, HAY QUE ASIGNAR UNA UBICACION (O "N") PARA CADA
-- ESTANTE, ALMACEN NUEVO. NO SE HACE POR SISTEMA SINO POR SQL
SELECT * FROM RS_ALMOV_UBICACION ORDER BY 1 DESC

INSERT INTO RS_ALMOV_UBICACION
(CUBICACION, CALMA, CESTANTE, FILA, COLUMNA)
VALUES ('0700','00MS','RACK-XX', '','')