USE [MODELADOR]
GO

DROP TABLE MATRIZ_COMPRA_TELA
GO
CREATE TABLE [dbo].[MATRIZ_COMPRA_TELA](
	[CODIGO]	CHAR(3)		PRIMARY KEY,
	[TIPO]		CHAR(1)		, -- C = COMPRA, S = SERVICIO
	[MOVIM]		VARCHAR(100),
	[ALMORI]	CHAR(4)		,
	[ALMDES]	CHAR(4)		,
	[OLDALM]	CHAR(4)		,
	[CODSER]	CHAR(10)	,
	[ENTREGA]	VARCHAR(100),
	[RECIBE]	VARCHAR(100),
	[LET1]		CHAR(1),
	[LET2]      CHAR(1),
	[USUARIO]	CHAR(10)	,
	[FECHA]		SMALLDATETIME
) ON [PRIMARY]

--delete MATRIZ_COMPRA_TELA where CODIGO = '013'

INSERT INTO MATRIZ_COMPRA_TELA SELECT '001','C', 'COMPRA HILO CRUDO',	'', '00H0','00HD','','','HILO CRUDO',	'', 'h', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '002','C', 'COMPRA HILO COLOR',	'', '00HT','00HD','','','HILO COLOR',	'', 'h', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '003','C', 'COMPRA TELA CRUDA',	'', '00M0','00MH','','','TELA CRUDA',	'', 'c', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '004','C', 'COMPRA TELA COLOR',	'', '00M7','00MT','','','TELA COLOR',	'', 't', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '005','C', 'COMPRA TELA ACABADA',	'', '00MD','00MT','','','TELA ACABADA', '', 't', 'SISTEMAS', GETDATE() 

INSERT INTO MATRIZ_COMPRA_TELA SELECT '006','S', 'TEÑIDO DE HILO',	  '00H0', '00HT','00HD','ST015','HILO CRUDO','HILO COLOR',	  'h','h', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '007','S', 'TEJIDO EN CRUDO',	  '00H0', '00M0','00MH','ST006','HILO CRUDO','TELA CRUDA',	  'h','c', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '008','S', 'TEJIDO EN COLOR',	  '00HT', '00M7','00MT','ST101','HILO COLOR','TELA COLOR',	  'h','t', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '009','S', 'TEÑIDO DE TELA',	  '00M0', '00M7','00MT','ST015','TELA CRUDA','TELA COLOR',	  'c','t', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '010','S', 'ESTAMPADO DE TELA', '00M7', '00MD','00MT','ST008','TELA COLOR','TELA ACABADA', 't','t', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '011','S', 'LAVADO DE TELA',	  '00M7', '00MD','00MT','ST9031','TELA COLOR','TELA ACABADA','t','t', 'SISTEMAS', GETDATE() 
INSERT INTO MATRIZ_COMPRA_TELA SELECT '012','S', 'ACABADO DE TELA',	  '00M7', '00MD','00MT','ST023','TELA COLOR','TELA ACABADA', 't','t', 'SISTEMAS', GETDATE() 
GO



SELECT * FROM MATRIZ_COMPRA_TELA