-- IDENTIFICA USUAARIO
Select * From RSFACCAR..UT0030 WHERE TU_ALIAS='sist'
-- CAPTURA PWD
Select TU_PASSWO From RSFACCAR..UT0030 Where TU_ALIAS='sist'
-- DATOS DE LA EMPRESA A LA QUE INGRESO EN EL SISTEMA
Select * From RSFACCAR..ALCIAS Where AC_CCIA='0001'
-- DATOS DE LA EMPRESA PARA CONTA
Select * From RSCONCAR..CTCIAS Where CT_CIA='0001'
Select * From RSCONCAR..CT0001CONT11
-- tablAS GENERALES -- REQUIERE CONFIGURACION DE FECHA Y AALMACEN? ==> S
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='FECLIB'
-- EL tg_CCOD = 00 ES EL INDICE GENERAL DE LA TABLA DE CLAVES
Select * From RSFACCAR..AL0001TABL order by 1,2
/*
00          	INDICE DE TABLAS
01          	TECNICOS
02          	LUGAR DE ORIGEN
03          	MONEDAS
04          	TIPOS DE DOCUMENTOS DE REFERENCIA
05          	UNIDAD DE MEDIDAS
06          	GRUPOS o SUBCLASE DE ARTICULOS
07          	CUENTAS CONTABLES
08          	TIPOS DE ARTICULO
09          	CATEGORIAS
10          	CENTRO DE COSTO
11          	RESPONSABLE DE CREDITOS
12          	SOLICITANTE AUTORIZADO: compra/mov.stock
13          	DISTRITOS
14          	CODIGOS DE AGENCIAS
15          	ESTADO DE REGISTROS
16          	TIPO DE ANEXO (ALTABM)
17          	STOCK AFECTADO (ALTABM)
18          	TIPO DE COSTEO
19          	TIPO DE MONEDA PARA FACTURACION O N/C
21          	LINEAS A REGISTRAR
22          	SISTEMA DE VENTAS
23          	TIPO DE PRECIO
24          	LINEAS DE VENTA
25          	CODIGOS DE TARJETAS DE CREDITO
27          	VENDEDORES
28          	ZONA DE VENTA
29          	COBRADORES
30          	TIPO DE PROVEEDOR
31          	SITUACION ORDEN COMPRA
35          	TIPO REPOSICION COMPRA
36          	CLASIFICACION ARTICULO
37          	TIPOS DE CONVERSION (T.Cambio)
38          	FAMILIAS o CLASE
39          	MODELOS
40          	DIAS DE ATENCION (visitas al cliente)
41          	ESTADO DEL CHEQUE
42          	TIPOS OPERACION CHEQUE
43          	SITUACION DE LETRAS
44          	TIPOS MOVIMIENTO COBRANZA
45          	AGENCIAS BANCARIAS (que cobran)
46          	TIPO DE DESCUENTO
47          	CADENAS DE CLIENTES
48          	LINEAS DE ARTICULO
50          	TRANSACCIONES DEPOSITO
51          	TIPOS DE LIQUIDACION
52          	FORMAS DE PAGO
53          	TIPO DE VENDEDOR
54          	SITUACION PEDIDOS
55          	SITUACION LIQUIDACION
56          	SITUACION DEL CHEQUE
58          	TERRITORIO
59          	RUTAS
60          	SEGMENTO
61          	UBICACION SEGMENTO
62          	GIRO NEGOCIO
63          	TIPO DE ORDEN DE COMPRA
65          	TIPO ATENCION
66          	ZONA POSTAL
67          	TIPO CLIENTE
68          	TIPO N.CREDITO
69          	MOVIMIENTOS DE CAJA
70          	RELACION BANCOS
71          	TABLA DE GASTOS E INTERESES (Pdte SM)
72          	AGENCIA - DOCUMENTOS
74          	AREAS
75          	ESTADO DE REQUERIMIENTO
76          	TIPO DE NOTA DE CREDIO
77          	EMBARQUES
80          	NOMBRE RESPONSABLE
81          	COLOR N/O
82          	TALLAS N/O
85          	TABLA DE FLAG CREDITOS
86          	TIPOS DOCUMENTOS IMPORTACION
89          	CODIGOS DE ALMACEN (para facturacion)
90          	DEPARTAMENTOS DE LA CIA
91          	TIPO DE USUARIOS
92          	TIPO DE IMPRESORA
93          	CONFIGURACION DE FECHA Y ALMACEN
94          	TIPOS DE FACTURAS
95          	PARAMETROS PARA ASIENTO DE VENTAS
97          	AGENCIA COBRANZA - SUBDIARIO
98          	PARAMETROS ASIENTO CTACTE clientes
99          	PORCENTAJES DE COMISION
*/
-- BUSCA EL ALMACEN AL QUE TIENE ACCESO EL USUARIO
Select TU_NROALM From RSFACCAR..UT0030 Where TU_ALIAS='sist '
-- 93          *****	CONFIGURACION DE FECHA Y ALMACEN
-- EN EL 93 HAY FLAGS, CUENTAS CONTABLES Y PARAMETROS PARA CONTAAA
-- ESTE PARAMETRO DICE QUE HAY QUE ACTIVAR AGENCIAS x USAUARIOS = N
Select TC_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUAGENCI'
-- FACTURACION LIBRO CAJA = CAJ01
Select TC_CDESCRI From RSFACCAR..FT0001TCAJ Where TC_CCOD='20' AND TC_CCLAVE='sist '
-- descripcion del almacén seleccionado???
Select A1_CDESCRI,A1_CCTLNUM,A1_CLOCALI From RSFACCAR..AL0001ALMA Where A1_CALMA='0001'
-- devuelve N
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUHCMA'
-- no devuelve nada
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUCAMSER'
-- no devuelve nada
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PULEVOLA'
-- no devuelve nada
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUNCLIB'
-- DEVUELVE == INICIO DE VALORIZACIONES
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUALVALO'
-- DEVUELVE N
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUIZA'
-- DEVUELVE s HAY PREVIEW EN GUIA Y FACTURA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUFORMOD'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUAYUVEN'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='CODGEN'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUNEUMA'
-- devuelve s  flag de atencion parcial a una cotizacion
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUATENCT'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUMEMO'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUFECINI'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUCODGRA'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='MENUV'
-- NO DEVUELVE NADA
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUCODCOR'
-- NO DEVUELVE NADA
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUCANDEC'
-- devuelve N
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUPAGPL'
-- DEVUELVE N  a flag de opciones de RP
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PURP'
-- DEVUELVE N A FLAG DE PEDIDO STANDARD
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUPEDSTD'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUCELU'
-- DEVUELVE N A ACTIVAR COMPUPALACE
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And TG_CCLAVE='PUPLC'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUDOCREF'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUREDOMN' 
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUREDOUS' 
-- DEVUELVE A
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUASIGSL'
-- DEVUELVE N A ASIENTO DE VENTAS EN LINEA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUVTALIN'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUCODREF'
-- DEVUELVE S
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUFILTIP'
-- DEVUELVE S
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUCOSDIA'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUDRAFT'
-- DEVUELVE N
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUVTOLOT'
-- DEVUELVE N a activar plan tarifario
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUPRECT'
-- devuelve N A FLAG OPCIONES LCA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PULCA'
-- devuelve n
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUMODCAJ'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUGRIFO'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUOCAPRO'
-- NO DEVUELVE NADA
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUOCNAPR'
-- devuelve N FLAG PARA ACTIVAR PERCEPCIONES
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUPERC'
-- DEVUELVE N
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUREST'
-- DEVUELVE S
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUMAYUS'
-- DEVUELVE S PARA REPROCESAR MOVIMIENTOS EN FACTURAS
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' AND TG_CCLAVE='PUREPRO'













Select * From RSFACCAR..AL0001TABL Where TG_CCOD='93' order by 2
/*********************************************/
/**********************************************/
-- abre grid de o/c
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And LEFT(TG_CCLAVE,7)='MODICOM'
Select TG_CDESCRI From RSFACCAR..AL0001TABL Where TG_CCOD='93' And LEFT(TG_CCLAVE,7)='PULWORD'




Select RTrim(Left(TG_CDESCRI, 40)) as Cad,* From RSFACCAR..AL0001TABL Where TG_CCOD='27' Order by RTrim(Left(TG_CDESCRI, 40))
-- COMBO DE TIPO DE MONEDA
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='03' Order by TG_CCLAVE
-- COMBO DE CENTROS DE COSTO
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='10' Order by TG_CCLAVE
-- COMBO DE ALMACENES
Select * From RSFACCAR..AL0001ALMA Order by A1_CALMA

-- CAJA PARA FACTURAR ??
Select TC_CDESCRI From RSFACCAR..FT0001TCAJ Where TC_CCOD='20' And TC_CCLAVE='sist '
-- tIPO DE CAJA???
Select TC_CDESCRI From RSFACCAR..FT0001TCAJ Where TC_CCOD='28' And TC_CCLAVE='CAJ01'
-- busca nombre proveedor por RUC en la grid
Select AC_CNOMBRE From RSCONCAR..CP0001MAES Where AC_CVANEXO='P' AND AC_CCODIGO='20100174759'
--busca el fax del provvedor
Select AC_CFAXACR From RSCONCAR..CP0001MAES Where AC_CVANEXO='P' And AC_CCODIGO='20100174759       '


-- busca tipo de cambio
Select XMEIMP2 From RSCONCAR..CTCAMB Where  XCODMON='US' AND Convert(datetime,XFECCAM2,103)=Convert(datetime,'14/12/2012 00:00:00',103)
-- devuelve las lineas que coincidan con el patron de mes/año/proveedor
Select OC_CNUMORD AS Cadebus, IMPORTE=CASE OC_CCODMON When 'US' Then OC_NIMPUS Else OC_NIMPMN END, TG_CDESCRI AS ESTADO, *  From RSFACCAR..CO0001MOVC Left Join 
RSFACCAR..AL0001TABL On OC_CSITORD=TG_CCLAVE  Where TG_CCOD='31'  And (OC_CCODPRO='20100174759') And (YEAR(CONVERT(DATETIME,OC_DFECDOC,103))= 
YEAR(Convert(datetime,'01/12/2012',103)) and MONTH(CONVERT(DATETIME,OC_DFECDOC,103))= MONTH(Convert(datetime,'01/12/2012',103)))
 Order by OC_CNUMORD,OC_DFECDOC
-- datos de cabecera de la O/c
Select * From RSFACCAR..CO0001MOVC Where OC_CNUMORD='0000023084          '
-- busca en el concar ...
Select name From RSCONCAR..sysobjects Where name='CPCIAE'
--  combo de forma de pago .....
Select * From RSCONCAR..CP0001TAGE Where TG_INDICE='51' Order By TG_DESCRI
--