SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		MABEL MOLINA
-- Create date: 10-2-2017
-- Description:	CREA EL BATCH PARA PASARLO 
--				TODAS LAS NOCHES PORQUE ES MUY 
--				MUY PESADO
-- =============================================
ALTER PROCEDURE SP_PASA_AJUSTES
AS
BEGIN
	SET NOCOUNT ON;
    SELECT PO INTO #TMP FROM POS WHERE CONVERT(VARCHAR(10), Fecha, 103)   = CONVERT(VARCHAR(10), GETDATE(), 103)  order by FECHA desc
	DECLARE @POS CHAR(25)
	WHILE (EXISTS(SELECT PO FROM #TMP))
		BEGIN
			SET @POS = (SELECT TOP 1 PO FROM #TMP )
			EXEC SP_INSERTA_AJUSTE @POS
			DELETE #TMP WHERE PO = @POS
		END
END
GO

