--DROP TABLE [dbo].[SPECS_GRUPOS]

GO
--DROP TABLE SPECRUTA
CREATE TABLE [dbo].[SPECRUTA](
	[SPEC]		[CHAR](10)  NOT NULL,
	[VER]		[CHAR](3)	NOT NULL,
	[LIN]		[char](3)	NOT NULL,
	[CODIGO]	[char](3)	NOT NULL,
	[USUARIO]	[CHAR](10),
	[FECHA]		smalldatetime not null default getdate(),
	[ESTADO]	[CHAR](1)	NOT NULL DEFAULT 'A'
	CONSTRAINT [PK_SPEC_PRO] PRIMARY KEY CLUSTERED 
(	[SPEC] ASC,
	[VER] ASC,
	[LIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
--DROP TABLE [dbo].[SPECS_MEDIDAS]
--DROP TABLE [dbo].[SPECS_GRUPOS]

SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[SPECS_MEDIDAS](
	[SPEC]		[CHAR](10)  NOT NULL,
	[VER]		[CHAR](3)	NOT NULL,
	[ORDEN]		[char](2)	NOT NULL,
	[GRUPO]		[char](3)	NOT NULL,
	[LIN]		[CHAR](2)	NOT NULL DEFAULT '00',
	[MEDIDA]	[CHAR](3)	NOT NULL,
	[TOLERA]	[CHAR](8) NOT NULL DEFAULT '',
	[T0]		[CHAR](8) NOT NULL DEFAULT '',
	[T1]		[CHAR](8) NOT NULL DEFAULT '',
	[T2]		[CHAR](8) NOT NULL DEFAULT '',
	[T3]		[CHAR](8) NOT NULL DEFAULT '',
	[T4]		[CHAR](8) NOT NULL DEFAULT '',
	[T5]		[CHAR](8) NOT NULL DEFAULT '',
	[T6]		[CHAR](8) NOT NULL DEFAULT '',
	[T7]		[CHAR](8) NOT NULL DEFAULT '',
	[T8]		[CHAR](8) NOT NULL DEFAULT '',
	[T9]		[CHAR](8) NOT NULL DEFAULT '',
	[T10]		[CHAR](8) NOT NULL DEFAULT '',
	[T11]		[CHAR](8) NOT NULL DEFAULT '',
	[T12]		[CHAR](8) NOT NULL DEFAULT '',
	[T13]		[CHAR](8) NOT NULL DEFAULT '',
	[T14]		[CHAR](8) NOT NULL DEFAULT '',
	[T15]		[CHAR](8) NOT NULL DEFAULT '',
	[T16]		[CHAR](8) NOT NULL DEFAULT '',
	[T17]		[CHAR](8) NOT NULL DEFAULT '',
	[T18]		[CHAR](8) NOT NULL DEFAULT '',
	[T19]		[CHAR](8) NOT NULL DEFAULT '',
	[T20]		[CHAR](8) NOT NULL DEFAULT '',
	[T21]		[CHAR](8) NOT NULL DEFAULT '',
	[T22]		[CHAR](8) NOT NULL DEFAULT '',
	[T23]		[CHAR](8) NOT NULL DEFAULT '',
	[T24]		[CHAR](8) NOT NULL DEFAULT '',
	[T25]		[CHAR](8) NOT NULL DEFAULT '',
	[T26]		[CHAR](8) NOT NULL DEFAULT '',
	[T27]		[CHAR](8) NOT NULL DEFAULT '',
	[T28]		[CHAR](8) NOT NULL DEFAULT '',
	[T29]		[CHAR](8) NOT NULL DEFAULT '',
	[T30]		[CHAR](8) NOT NULL DEFAULT ''
	CONSTRAINT [PK_SPEC_MED] PRIMARY KEY CLUSTERED 
(	[SPEC] ASC,
	[VER] ASC,
	[ORDEN] ASC,
	[GRUPO] ASC,
	[LIN]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
