
CREATE TABLE [SUBFAMILIAS] (
		[FAMTELA]		CHAR(2) NOT NULL PRIMARY KEY REFERENCES [FAMTELAS](FAMTELA),
		[SUBFAM]		CHAR(2)	NOT NULL,
		[DESCRIPCION]	CHAR (100) NOT NULL,
		[USUARIO]		char(10) NOT NULL,
		[FECHA]			SMALLDATETIME DEFAULT GETDATE() NOT NULL,
		[ESTADO]		CHAR(1) DEFAULT 'A' NOT NULL
)
ON [PRIMARY]
GO

