
CREATE TABLE [SUGERIDOCCT] (
		[INICIO]		INT NOT NULL PRIMARY KEY,
		[FIN]			INT NOT NULL,
		[NUMROLLO]		INT NOT NULL,
		[USUARIO]		char(10) NOT NULL,
		[FECHA]			SMALLDATETIME DEFAULT GETDATE() NOT NULL,
		[ESTADO]		CHAR(1) DEFAULT 'A' NOT NULL
)
ON [PRIMARY]
GO

