
CREATE TABLE [COTIRUTA] (
		[COTIZACION]	CHAR(10) REFERENCES [COTIZACION](COTIZACION) NOT NULL,
		[TELA]			char(6) REFERENCES [TELAS](TELA) NOT NULL,
		[ID]			INT NOT NULL,
		[SERVICIO]		char(6) NOT NULL REFERENCES [SERVICIOS](CODIGO),
		[ORDEN]			INT NOT NULL,
		[MERMA]			NUMERIC(5,2) DEFAULT 0 NOT NULL,
		[COSTO]			NUMERIC(5,2),
		[UNIDAD]		CHAR(3) NOT NULL DEFAULT 'KGR',
		[USUARIO]		char(10) NOT NULL,
		[FECHA]			SMALLDATETIME DEFAULT GETDATE() NOT NULL,
		[ESTADO]		CHAR(1) DEFAULT 'A' NOT NULL
)
ON [PRIMARY]
GO
ALTER TABLE [COTIRUTA]
	ADD
	CONSTRAINT [PK_COTIRUTA]
	PRIMARY KEY
	([COTIZACION], [TELA], [ID], [SERVICIO], [ORDEN])
	ON [PRIMARY]
GO
