CREATE VIEW VIEW_AJUSTES
AS
SELECT        TOP (100) PERCENT dbo.AJUSTES.AJUSTE AS AJU, dbo.AJUSTES.[VERSION] AS VER, dbo.AJUSTES.CLIENTE AS CLI, dbo.CLIENTE.NOMBRE AS NOM, 
                         dbo.AJUSTES.ESTILO AS EST, dbo.ESTILOS.ESTCLI AS ECL, dbo.ESTILOS.DESCRIPCION AS DES, dbo.ESTILOS.CODARTICULO AS ART, 
                         dbo.ESTILOS.GENERO AS GEN, dbo.GENEROS.DESCRIPCION AS DGEN, dbo.ESTILOS.TIPOPRENDA AS TIP, dbo.TIPPRENDA.DESCRIPCION AS TPRE, 
                         dbo.AJUSTES.TELA AS TEL, dbo.TELAS.DESCRIPCION AS DTEL, dbo.AJUSTES.TEMPORADA AS TEM, dbo.TEMPORADAS.DESCRIPCION AS DTEM, 
                         dbo.AJUSTES.MOTIVO AS MOT, LEFT(LTRIM(RTRIM(dbo.AJUSTES.OBS)), 50) AS ADIC, dbo.AJUSTES.ESTADO AS EDO
FROM    dbo.AJUSTES 
		INNER JOIN dbo.ESTILOS ON dbo.AJUSTES.CLIENTE = dbo.ESTILOS.CLIENTE AND dbo.AJUSTES.ESTILO = dbo.ESTILOS.CODEST 
		INNER JOIN dbo.TELAS ON dbo.AJUSTES.TELA = dbo.TELAS.TELA 
		INNER JOIN dbo.TEMPORADAS ON dbo.AJUSTES.TEMPORADA = dbo.TEMPORADAS.CODIGO AND dbo.AJUSTES.CLIENTE = dbo.TEMPORADAS.CLIENTE 
		INNER JOIN dbo.CLIENTE ON dbo.ESTILOS.CLIENTE = dbo.CLIENTE.CODIGO AND dbo.TEMPORADAS.CLIENTE = dbo.CLIENTE.CODIGO 
		INNER JOIN dbo.GENEROS ON dbo.ESTILOS.GENERO = dbo.GENEROS.GENERO 
		INNER JOIN dbo.TIPPRENDA ON dbo.ESTILOS.TIPOPRENDA = dbo.TIPPRENDA.TIPO
WHERE        (dbo.AJUSTES.ESTADO = 'a')
ORDER BY AJU, VER