--select * from rsv_tela
CREATE VIEW VIEW_RESERVAS 
AS
SELECT OO.*, CLI, NOM, COTI, CANT AS PEDIDO, FOT, CON, CODEST, ESTCLI, DESEST, CGEN, DGEN, TPRE, DPRE, CART, FOB, PROTO AS AJUSTE, VER 

FROM (
-- TELA CRUDA
select TIPO, AA.OFI,AA.PO, AA.ALM, AA.CODIGO, 
KG= (SELECT SUM(CC.KGS) FROM RSV_Tela CC WHERE TIPO = 'C' and  CC.CODIGO = CRUDO+'0000000000' AND CC.OFI= AA.OFI AND CC.PO=AA.PO  ),
qt= (SELECT SUM(CC.qty) FROM RSV_Tela CC WHERE TIPO = 'C' and  CC.CODIGO = CRUDO+'0000000000' AND CC.OFI= AA.OFI AND CC.PO=AA.PO  ),
RKG= SUM(BB.KGS), RQT= (SUM(BB.QTY)), AA.ESTADO  
FROM RSV_TELA AA INNER JOIN EXPLOSION_TELA BB
ON aa.ofi = bb.ofi and aa.po= bb.po and CRUDO+'0000000000' = CODIGO 
GROUP BY AA.OFI, AA.PO, AA.ESTADO, ALM, CODIGO, CRUDO,TIPO
UNION
-- TELA COLOR
select TIPO, AA.OFI,AA.PO, AA.ALM, AA.CODIGO, 
KG= (SELECT SUM(CC.KGS) FROM RSV_Tela CC WHERE TIPO = 'T' and  CC.CODIGO = TELA AND CC.OFI= AA.OFI AND CC.PO=AA.PO  ),
qt= (SELECT SUM(CC.qty) FROM RSV_Tela CC WHERE TIPO = 'T' and  CC.CODIGO = TELA AND CC.OFI= AA.OFI AND CC.PO=AA.PO  ),
RKG= SUM(BB.KGS), RQT= (SUM(BB.QTY)), AA.ESTADO  
FROM RSV_TELA AA INNER JOIN EXPLOSION_TELA BB
ON aa.ofi = bb.ofi and aa.po= bb.po and TELA = CODIGO 
GROUP BY AA.OFI, AA.PO, AA.ESTADO, ALM, CODIGO, TELA,TIPO

UNION

--HILADO CRUDO
select TIPO, AA.OFI,AA.PO, AA.ALM, AA.CODIGO, 
KG= (SELECT SUM(CC.KGS) FROM RSV_Tela CC WHERE TIPO = 'H' and  CC.CODIGO = H1 AND CC.OFI= AA.OFI AND CC.PO=AA.PO  ),
qt= 0,
RKG= SUM(BB.KGS), RQT= 0, AA.ESTADO  
FROM RSV_TELA AA INNER JOIN EXPLOSION_TELA BB
ON aa.ofi = bb.ofi and aa.po= bb.po and H1 = CODIGO 
GROUP BY AA.OFI, AA.PO, AA.ESTADO, ALM, CODIGO, H1,TIPO

UNION
select TIPO, AA.OFI,AA.PO, AA.ALM, AA.CODIGO, 
KG= (SELECT SUM(CC.KGS) FROM RSV_Tela CC WHERE TIPO = 'H' and  CC.CODIGO = H2 AND CC.OFI= AA.OFI AND CC.PO=AA.PO  ),
qt= 0,
RKG= SUM(BB.KGS), RQT= 0, AA.ESTADO  
FROM RSV_TELA AA INNER JOIN EXPLOSION_TELA BB
ON aa.ofi = bb.ofi and aa.po= bb.po and H2 = CODIGO 
GROUP BY AA.OFI, AA.PO, AA.ESTADO, ALM, CODIGO, H2,TIPO

UNION
select TIPO, AA.OFI,AA.PO, AA.ALM, AA.CODIGO, 
KG= (SELECT SUM(CC.KGS) FROM RSV_Tela CC WHERE TIPO = 'H' and  CC.CODIGO = H3 AND CC.OFI= AA.OFI AND CC.PO=AA.PO  ),
qt= 0,
RKG= SUM(BB.KGS), RQT= 0, AA.ESTADO  
FROM RSV_TELA AA INNER JOIN EXPLOSION_TELA BB
ON aa.ofi = bb.ofi and aa.po= bb.po and H3 = CODIGO 
GROUP BY AA.OFI, AA.PO, AA.ESTADO, ALM, CODIGO, H3,TIPO

UNION
select TIPO, AA.OFI,AA.PO, AA.ALM, AA.CODIGO, 
KG= (SELECT SUM(CC.KGS) FROM RSV_Tela CC WHERE TIPO = 'H' and  CC.CODIGO = H4 AND CC.OFI= AA.OFI AND CC.PO=AA.PO  ),
qt= 0,
RKG= SUM(BB.KGS), RQT= 0, AA.ESTADO  
FROM RSV_TELA AA INNER JOIN EXPLOSION_TELA BB
ON aa.ofi = bb.ofi and aa.po= bb.po and H4 = CODIGO 
GROUP BY AA.OFI, AA.PO, AA.ESTADO, ALM, CODIGO, H4,TIPO
UNION
select TIPO,  AA.OFI,AA.PO, AA.ALM, AA.CODIGO, 
KG= (SELECT SUM(CC.KGS) FROM RSV_Tela CC WHERE TIPO = 'H' and  CC.CODIGO = H5 AND CC.OFI= AA.OFI AND CC.PO=AA.PO  ),
qt= 0,
RKG= SUM(BB.KGS), RQT= 0, AA.ESTADO  
FROM RSV_TELA AA INNER JOIN EXPLOSION_TELA BB
ON aa.ofi = bb.ofi and aa.po= bb.po and H5 = CODIGO 
GROUP BY AA.OFI, AA.PO, AA.ESTADO, ALM, CODIGO, H5,TIPO

UNION
select TIPO, AA.OFI,AA.PO, AA.ALM, AA.CODIGO, 
KG= (SELECT SUM(CC.KGS) FROM RSV_Tela CC WHERE TIPO = 'H' and  CC.CODIGO = H6 AND CC.OFI= AA.OFI AND CC.PO=AA.PO  ),
qt= 0,
RKG= SUM(BB.KGS), RQT= 0, AA.ESTADO  
FROM RSV_TELA AA INNER JOIN EXPLOSION_TELA BB
ON aa.ofi = bb.ofi and aa.po= bb.po and H6 = CODIGO 
GROUP BY AA.OFI, AA.PO, AA.ESTADO, ALM, CODIGO, H6,TIPO)OO
inner join VIEW_OFIS vv on oo.ofi = vv.ofi


