CREATE VIEW VIEW_TELAS_RHIN
AS
SELECT      AR_CCODIGO, AR_CDESCRI, AR_CDESCR2, AR_CCODIG2, AR_CUNIDAD, AR_CCUENTA, AR_NPRECI1, AR_NPRECI2, AR_NPRECI3, AR_NPRECI4, AR_NPRECI5, 
            AR_NPRECI6, AR_CMONVTA, AR_NIGVPOR, AR_NISCPOR, AR_CTIPO, AR_CCONTRO, AR_CTIPDES, AR_NDESCTO, AR_NDESCT2, AR_NPDIS, AR_NPCOM, 
            AR_CGRUPO, AR_CFAMILI, AR_CMODELO, AR_CLINEA, AR_NPESO, AR_NVOLUME, AR_NAREA, AR_NFACTOR, AR_NANCHO, AR_NLARGO, AR_CMONCOS, 
            AR_NPRECOS, AR_DFECCOS, AR_CMONCOM, AR_NPRECOM, AR_DFECCOM, AR_CCODPRO, AR_CMONFOB, AR_NPREFOB, AR_NMARGE1, AR_NMARGE2, 
            AR_CCLAART, AR_CPARARA, AR_CINFTEC, AR_CCATALO, AR_CCATEGO, AR_CTIPOI, AR_TOBSERV, AR_CUNIREF, AR_NFACREF, AR_CFUNIRE, AR_CFSTOCK, 
            AR_CFDECI, AR_CFPRELI, AR_CFRESTA, AR_CFSERIE, AR_CFLOTE, AR_CFROTAB, AR_CUSUCRE, AR_CUSUMOD, AR_CESTADO, AR_DFECCRE, AR_DFECMOD, 
            AR_CCODANT, AR_NDETRA, AR_CMEDIDA, AR_CANNO, AR_CGROSOR, AR_NIMAGEN, AR_CFECABC, AR_NLONSER, AR_CFCELU, AR_NLONCEL, AR_CMEDNEU, 
            AR_CINDCAR, AR_CDISENO, AR_NPERC1, AR_NPERC2, AR_CMARCA, AR_CANOFAB, AR_CLUGORI, AR_CFVEHI, AR_CAYUVEN, AR_CCOLOR, AR_CTALLA, 
            AR_CTIPEXI, AR_NMARVTA, AR_CHORSER, AR_NIGVCPR, AR_CCUENTR, AR_CFLGRCN, AR_NTASRCN, AR_CFORSER, AR_CCODAG1, AR_CCODAG2, AR_CCODAG3, 
            AR_CCODAG4, AR_CCODAG5, AR_PERTOPE, AR_CTASTIP, AR_CTASISC, AR_CTASMON, AR_NTASEQU, AR_CTASUNI, AR_CTSIISC, AR_CTIPTAS, AR_CAFEDET
FROM        RSFACCAR.dbo.AL0001ARTI AS ARTI
WHERE       (AR_CLINEA = '0007') AND (AR_CESTADO = 'V') AND (AR_CMODELO='TELAS')
