SELECT        PT.CLI, PT.NOM, PT.PO, PT.ESTCLI, PT.OFI, PT.COLOR, PT.XS, PT.S, PT.M, PT.L, PT.XL, PT.XXL, PT.[3XL], PT.[4XL], PT.[5XL], PT.[6XL], PT.[7XL], PT.[8XL],
PT.[LT], PT.[XLT], PT.[2XLT], PT.[3XLT], PT.[4XLT], PT.TOTAL, 
CEILING(PT.XS * 1.05) AS _XS, CEILING(PT.S * 1.05) AS _S, CEILING(PT.M * 1.05) AS _M, CEILING(PT.L * 1.05) AS _L, CEILING(PT.XL * 1.05) AS _XL, 
CEILING(PT.XXL * 1.05) AS _XXL, CEILING(PT.[3XL] * 1.05) AS _3XL, CEILING(PT.[4XL] * 1.05) AS _4XL, CEILING(PT.[5XL] * 1.05) AS _5XL, CEILING(PT.[6XL] * 1.05) 
AS _6XL, CEILING(PT.[7XL] * 1.05) AS _7XL, CEILING(PT.[8XL] * 1.05) AS _8XL, CEILING(PT.[LT] * 1.05) AS _LT,  CEILING(PT.[XLT] * 1.05) AS _XLT,  CEILING(PT.[2XLT] * 1.05) AS _2XLT,  CEILING(PT.[3XLT] * 1.05) AS _3XLT,  CEILING(PT.[4XLT] * 1.05) AS _4XLT, 

CEILING(PT.XS * 1.05) + CEILING(PT.S * 1.05) + CEILING(PT.M * 1.05) + CEILING(PT.L * 1.05) + CEILING(PT.XL * 1.05) + CEILING(PT.XXL * 1.05) + CEILING(PT.[3XL] * 1.05) + CEILING(PT.[4XL] * 1.05) + CEILING(PT.[5XL] * 1.05) + CEILING(PT.[6XL] * 1.05) + CEILING(PT.[7XL] * 1.05) + CEILING(PT.[8XL] * 1.05) 
+ CEILING(PT.[LT] * 1.05)+ CEILING(PT.[XLT] * 1.05)+ CEILING(PT.[2XLT] * 1.05)+ CEILING(PT.[3XLT] * 1.05)+ CEILING(PT.[4XLT] * 1.05)AS _TOTAL, 

PT.TEMPO, PT.FABRIC, PT.LLEGAPO, PT.ESTADO, PT.CODTEM, 
PD.CODIGO, PD.PESO / 1000 AS peso, PD.CONSUMO, PD.CANPZA, PD.ID, PD.AJUSTE, PD.VERSION, PD.AJUSTE + '-' + PD.VERSION AS ajuste2
FROM            dbo.View_PEDIDO_TELA AS PT INNER JOIN
                         dbo.[AJUSTE-DETALLES] AS PD ON PT.AJUSTE = PD.AJUSTE AND PT.VERSION = PD.VERSION
WHERE        (PD.TIPODETALLE = 'TE')