SELECT        dbo.VIEW_PROGRAMA_DESPACHOS.CLI, dbo.VIEW_PROGRAMA_DESPACHOS.NOM, dbo.VIEW_PROGRAMA_DESPACHOS.PO, 
                         dbo.VIEW_PROGRAMA_DESPACHOS.ESTCLI, dbo.VIEW_PROGRAMA_DESPACHOS.OFI, PD.COLOR, 
                         ISNULL(CASE WHEN T0 = 'XS' THEN CAN0 WHEN T1 = 'XS' THEN CAN1 WHEN T2 = 'XS' THEN CAN2 WHEN T3 = 'XS' THEN CAN3 WHEN T4 = 'XS' THEN CAN4 WHEN
                          T5 = 'XS' THEN CAN5 WHEN T6 = 'XS' THEN CAN6 WHEN T7 = 'XS' THEN CAN7 WHEN T8 = 'XS' THEN CAN8 WHEN T9 = 'XS' THEN CAN9 END, 0) AS XS, 
                         ISNULL(CASE WHEN T0 = 'S' THEN CAN0 WHEN T1 = 'S' THEN CAN1 WHEN T2 = 'S' THEN CAN2 WHEN T3 = 'S' THEN CAN3 WHEN T4 = 'S' THEN CAN4 WHEN T5 = 'S'
                          THEN CAN5 WHEN T6 = 'S' THEN CAN6 WHEN T7 = 'S' THEN CAN7 WHEN T8 = 'S' THEN CAN8 WHEN T9 = 'S' THEN CAN9 END, '0') AS S, 
                         ISNULL(CASE WHEN T0 = 'M' THEN CAN0 WHEN T1 = 'M' THEN CAN1 WHEN T2 = 'M' THEN CAN2 WHEN T3 = 'M' THEN CAN3 WHEN T4 = 'M' THEN CAN4 WHEN T5 =
                          'M' THEN CAN5 WHEN T6 = 'M' THEN CAN6 WHEN T7 = 'M' THEN CAN7 WHEN T8 = 'M' THEN CAN8 WHEN T9 = 'M' THEN CAN9 END, 0) AS M, 
                         ISNULL(CASE WHEN T0 = 'L' THEN CAN0 WHEN T1 = 'L' THEN CAN1 WHEN T2 = 'L' THEN CAN2 WHEN T3 = 'L' THEN CAN3 WHEN T4 = 'L' THEN CAN4 WHEN T5 = 'L'
                          THEN CAN5 WHEN T6 = 'L' THEN CAN6 WHEN T7 = 'L' THEN CAN7 WHEN T8 = 'L' THEN CAN8 WHEN T9 = 'L' THEN CAN9 END, 0) AS L, 
                         ISNULL(CASE WHEN T0 = 'XL' THEN CAN0 WHEN T1 = 'XL' THEN CAN1 WHEN T2 = 'XL' THEN CAN2 WHEN T3 = 'XL' THEN CAN3 WHEN T4 = 'XL' THEN CAN4 WHEN
                          T5 = 'XL' THEN CAN5 WHEN T6 = 'XL' THEN CAN6 WHEN T7 = 'XL' THEN CAN7 WHEN T8 = 'XL' THEN CAN8 WHEN T9 = 'XL' THEN CAN9 END, 0) AS XL, 
                         ISNULL(CASE WHEN T0 = 'XXL' THEN CAN0 WHEN T1 = 'XXL' THEN CAN1 WHEN T2 = 'XXL' THEN CAN2 WHEN T3 = 'XXL' THEN CAN3 WHEN T4 = 'XXL' THEN CAN4
                          WHEN T5 = 'XXL' THEN CAN5 WHEN T6 = 'XXL' THEN CAN6 WHEN T7 = 'XXL' THEN CAN7 WHEN T8 = 'XXL' THEN CAN8 WHEN T9 = 'XXL' THEN CAN9 END, 0) 
                         AS XXL, 
                         ISNULL(CASE WHEN T0 = '3XL' THEN CAN0 WHEN T1 = '3XL' THEN CAN1 WHEN T2 = '3XL' THEN CAN2 WHEN T3 = '3XL' THEN CAN3 WHEN T4 = '3XL' THEN CAN4 WHEN
                          T5 = '3XL' THEN CAN5 WHEN T6 = '3XL' THEN CAN6 WHEN T7 = '3XL' THEN CAN7 WHEN T8 = '3XL' THEN CAN8 WHEN T9 = '3XL' THEN CAN9 END, 0) AS [3XL], 
                         ISNULL(CASE WHEN T0 = '4XL' THEN CAN0 WHEN T1 = '4XL' THEN CAN1 WHEN T2 = '4XL' THEN CAN2 WHEN T3 = '4XL' THEN CAN3 WHEN T4 = '4XL' THEN CAN4 WHEN
                          T5 = '4XL' THEN CAN5 WHEN T6 = '4XL' THEN CAN6 WHEN T7 = '4XL' THEN CAN7 WHEN T8 = '4XL' THEN CAN8 WHEN T9 = '4XL' THEN CAN9 END, 0) AS [4XL], 
                         ISNULL(CASE WHEN T0 = '5XL' THEN CAN0 WHEN T1 = '5XL' THEN CAN1 WHEN T2 = '5XL' THEN CAN2 WHEN T3 = '5XL' THEN CAN3 WHEN T4 = '5XL' THEN CAN4 WHEN
                          T5 = '5XL' THEN CAN5 WHEN T6 = '5XL' THEN CAN6 WHEN T7 = '5XL' THEN CAN7 WHEN T8 = '5XL' THEN CAN8 WHEN T9 = '5XL' THEN CAN9 END, 0) AS [5XL], 
                         ISNULL(CASE WHEN T0 = '6XL' THEN CAN0 WHEN T1 = '6XL' THEN CAN1 WHEN T2 = '6XL' THEN CAN2 WHEN T3 = '6XL' THEN CAN3 WHEN T4 = '6XL' THEN CAN4 WHEN
                          T5 = '6XL' THEN CAN5 WHEN T6 = '6XL' THEN CAN6 WHEN T7 = '6XL' THEN CAN7 WHEN T8 = '6XL' THEN CAN8 WHEN T9 = '6XL' THEN CAN9 END, 0) AS [6XL], 
                         ISNULL(CASE WHEN T0 = '7XL' THEN CAN0 WHEN T1 = '7XL' THEN CAN1 WHEN T2 = '7XL' THEN CAN2 WHEN T3 = '7XL' THEN CAN3 WHEN T4 = '7XL' THEN CAN4 WHEN
                          T5 = '7XL' THEN CAN5 WHEN T6 = '7XL' THEN CAN6 WHEN T7 = '7XL' THEN CAN7 WHEN T8 = '7XL' THEN CAN8 WHEN T9 = '7XL' THEN CAN9 END, 0) AS [7XL], 
                         ISNULL(CASE WHEN T0 = '8XL' THEN CAN0 WHEN T1 = '8XL' THEN CAN1 WHEN T2 = '8XL' THEN CAN2 WHEN T3 = '8XL' THEN CAN3 WHEN T4 = '8XL' THEN CAN4 WHEN
                          T5 = '8XL' THEN CAN5 WHEN T6 = '8XL' THEN CAN6 WHEN T7 = '8XL' THEN CAN7 WHEN T8 = '8XL' THEN CAN8 WHEN T9 = '8XL' THEN CAN9 END, 0) AS [8XL], 
						 ISNULL(CASE WHEN T0 = 'LT' THEN CAN0 WHEN T1 = 'LT' THEN CAN1 WHEN T2 = 'LT' THEN CAN2 WHEN T3 = 'LT' THEN CAN3 WHEN T4 = 'LT' THEN CAN4 WHEN
                         T5 = 'LT' THEN CAN5 WHEN T6 = 'LT' THEN CAN6 WHEN T7 = 'LT' THEN CAN7 WHEN T8 = 'LT' THEN CAN8 WHEN T9 = 'LT' THEN CAN9 END, 0) AS [LT], 
						 ISNULL(CASE WHEN T0 = 'XLT' THEN CAN0 WHEN T1 = 'XLT' THEN CAN1 WHEN T2 = 'XLT' THEN CAN2 WHEN T3 = 'XLT' THEN CAN3 WHEN T4 = 'XLT' THEN CAN4 WHEN
                         T5 = 'XLT' THEN CAN5 WHEN T6 = 'XLT' THEN CAN6 WHEN T7 = 'XLT' THEN CAN7 WHEN T8 = 'XLT' THEN CAN8 WHEN T9 = 'XLT' THEN CAN9 END, 0) AS [XLT], 
						 ISNULL(CASE WHEN T0 = '2XLT' THEN CAN0 WHEN T1 = '2XLT' THEN CAN1 WHEN T2 = '2XLT' THEN CAN2 WHEN T3 = '2XLT' THEN CAN3 WHEN T4 = '2XLT' THEN CAN4 WHEN
                         T5 = '2XLT' THEN CAN5 WHEN T6 = '2XLT' THEN CAN6 WHEN T7 = '2XLT' THEN CAN7 WHEN T8 = '2XLT' THEN CAN8 WHEN T9 = '2XLT' THEN CAN9 END, 0) AS [2XLT], 
						 ISNULL(CASE WHEN T0 = '3XLT' THEN CAN0 WHEN T1 = '3XLT' THEN CAN1 WHEN T2 = '3XLT' THEN CAN2 WHEN T3 = '3XLT' THEN CAN3 WHEN T4 = '3XLT' THEN CAN4 WHEN
                         T5 = '3XLT' THEN CAN5 WHEN T6 = '3XLT' THEN CAN6 WHEN T7 = '3XLT' THEN CAN7 WHEN T8 = '3XLT' THEN CAN8 WHEN T9 = '3XLT' THEN CAN9 END, 0) AS [3XLT], 
						 ISNULL(CASE WHEN T0 = '4XLT' THEN CAN0 WHEN T1 = '4XLT' THEN CAN1 WHEN T2 = '4XLT' THEN CAN2 WHEN T3 = '4XLT' THEN CAN3 WHEN T4 = '4XLT' THEN CAN4 WHEN
                         T5 = '4XLT' THEN CAN5 WHEN T6 = '4XLT' THEN CAN6 WHEN T7 = '4XLT' THEN CAN7 WHEN T8 = '4XLT' THEN CAN8 WHEN T9 = '4XLT' THEN CAN9 END, 0) AS [4XLT], 

                         PD.CAN0 + PD.CAN1 + PD.CAN2 + PD.CAN3 + PD.CAN4 + PD.CAN5 + PD.CAN6 + PD.CAN7 + PD.CAN8 + PD.CAN9 AS TOTAL, 
                         REPLACE(dbo.VIEW_PROGRAMA_DESPACHOS.DESTEMPORADA, ' ', '') AS TEMPO, dbo.VIEW_PROGRAMA_DESPACHOS.FABRIC, 
                         dbo.VIEW_PROGRAMA_DESPACHOS.LLEGAPO, dbo.VIEW_PROGRAMA_DESPACHOS.ESTADO, dbo.VIEW_PROGRAMA_DESPACHOS.CODTEM, 
                         dbo.VIEW_PROGRAMA_DESPACHOS.AJUSTE, dbo.VIEW_PROGRAMA_DESPACHOS.VERSION
FROM            dbo.VIEW_PROGRAMA_DESPACHOS INNER JOIN
                         dbo.[PO-DETA] AS PD ON dbo.VIEW_PROGRAMA_DESPACHOS.PO = PD.PO